[package]
name = "launch-soundpad"
version = "0.1.0"
authors = ["Lucas Perreau"]
description = "A soundpad with Launchpad"
edition = "2021"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.66"
cpal = "0.14.1"
iced = "0.4.2"
lazy_static = "1.4.0"
midir = "0.8.0"
rodio = "0.16.0"
